
// Open UI.MENU
PRINT @12
SILENT
LAUNCH_ACTION_MACRO UIMenuOpen
ACTION_IF NOT $UIMenuIF("Succeeded") THEN
BEGIN
	FAIL @20
END

ACTION_MATCH 1
WITH
	%IsBG2% %IsLeUIBG2%
	BEGIN
		// Copy override files
		PRINT @24
		SILENT
		COPY ~%PKGNAME%/copy/ModsOptions/M_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/en_HideO.lua~ ~override~

		// Look for previously installed 	
		OUTER_SPRINT $UIMenuIF("MenuName") ~OPTIONS_HIDDEN~
		OUTER_SPRINT $UIMenuIF("Body") ~~
		LAUNCH_ACTION_MACRO UIMenuGetMenu
		ACTION_IF NOT $UIMenuIF("Succeeded") THEN
		BEGIN
			PRINT @101002
			SILENT
			OUTER_SPRINT $UIMenuIF("Filespec") ~%PKGNAME%/menu/ModsOptions/modohidden3.menu~
			LAUNCH_ACTION_MACRO UIMenuAppendFile
			ACTION_IF NOT $UIMenuIF("Succeeded") THEN
			BEGIN
				FAIL @101004
			END
		END ELSE
		BEGIN
			// Already installed
			PRINT @101003
		END
	END

	%IsEETBG2%
	BEGIN
		// Copy override files
		PRINT @24
		SILENT
		COPY ~%PKGNAME%/copy/ModsOptions/M_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/en_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/modoimg1.bam~ ~override~

		// Look for previously installed 	
		OUTER_SPRINT $UIMenuIF("MenuName") ~OPTIONS_HIDDEN~
		OUTER_SPRINT $UIMenuIF("Body") ~~
		LAUNCH_ACTION_MACRO UIMenuGetMenu
		ACTION_IF NOT $UIMenuIF("Succeeded") THEN
		BEGIN
			PRINT @101002
			SILENT
			OUTER_SPRINT $UIMenuIF("Filespec") ~%PKGNAME%/menu/ModsOptions/modohidden3.menu~
			LAUNCH_ACTION_MACRO UIMenuAppendFile
			ACTION_IF NOT $UIMenuIF("Succeeded") THEN
			BEGIN
				FAIL @101004
			END
		END ELSE
		BEGIN
			// Already installed
			PRINT @101003
		END
	END

	%IsBG2onSoD% %IsLeUISOD% %IsLeUIBG1% %IsEETLeUI%
	BEGIN
		// Copy override files
		PRINT @24
		SILENT
		COPY ~%PKGNAME%/copy/ModsOptions/en_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/M_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/GUIMGX.MOS~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/MODOPBG2.BAM~ ~override~

		// Look for previously installed 	
		OUTER_SPRINT $UIMenuIF("MenuName") ~OPTIONS_HIDDEN~
		OUTER_SPRINT $UIMenuIF("Body") ~~
		LAUNCH_ACTION_MACRO UIMenuGetMenu
		ACTION_IF NOT $UIMenuIF("Succeeded") THEN
		BEGIN
			// Append Hidden Game Options to UI.MENU
			PRINT @101002
			SILENT
			OUTER_SPRINT $UIMenuIF("Filespec") ~%PKGNAME%/menu/ModsOptions/modohidden2.menu~
			LAUNCH_ACTION_MACRO UIMenuAppendFile
			ACTION_IF NOT $UIMenuIF("Succeeded") THEN
			BEGIN
				FAIL @101004
			END
		END ELSE
		BEGIN
			// Already installed
			PRINT @101003
		END
	END

	%IsBGEE%
	BEGIN
		PRINT @17
		SILENT
		COPY ~%PKGNAME%/copy/ModsOptions/en_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/M_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/MODOPEE.BAM~ ~override~

		// Look for previously installed 	
		OUTER_SPRINT $UIMenuIF("MenuName") ~OPTIONS_HIDDEN~
		OUTER_SPRINT $UIMenuIF("Body") ~~
		LAUNCH_ACTION_MACRO UIMenuGetMenu
		ACTION_IF NOT $UIMenuIF("Succeeded") THEN
		BEGIN
			// Append Hidden Game Options to UI.MENU
			PRINT @101002
			SILENT
			OUTER_SPRINT $UIMenuIF("Filespec") ~%PKGNAME%/menu/ModsOptions/modohidden4.menu~
			LAUNCH_ACTION_MACRO UIMenuAppendFile
			ACTION_IF NOT $UIMenuIF("Succeeded") THEN
			BEGIN
				FAIL @101004
			END
		END ELSE
		BEGIN
			// Already installed
			PRINT @101003
		END
	END

	%IsSoDOverhaul%
	BEGIN
		PRINT @17
		SILENT
		COPY ~%PKGNAME%/copy/ModsOptions/en_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/M_HideO2.lua~ ~override~

		// Look for previously installed 	
		OUTER_SPRINT $UIMenuIF("MenuName") ~OPTIONS_HIDDEN~
		OUTER_SPRINT $UIMenuIF("Body") ~~
		LAUNCH_ACTION_MACRO UIMenuGetMenu
		ACTION_IF NOT $UIMenuIF("Succeeded") THEN
		BEGIN
			// Append Hidden Game Options to UI.MENU
			PRINT @101002
			SILENT
			OUTER_SPRINT $UIMenuIF("Filespec") ~%PKGNAME%/menu/ModsOptions/modohidden1.menu~
			LAUNCH_ACTION_MACRO UIMenuAppendFile
			ACTION_IF NOT $UIMenuIF("Succeeded") THEN
			BEGIN
				FAIL @101004
			END
		END ELSE BEGIN
			// Already installed
			PRINT @101003
		END
	END
	
	%IsEETSoD% %IsSoD%
	BEGIN
		PRINT @17
		SILENT
		COPY ~%PKGNAME%/copy/ModsOptions/en_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/M_HideO.lua~ ~override~

		// Look for previously installed 	
		OUTER_SPRINT $UIMenuIF("MenuName") ~OPTIONS_HIDDEN~
		OUTER_SPRINT $UIMenuIF("Body") ~~
		LAUNCH_ACTION_MACRO UIMenuGetMenu
		ACTION_IF NOT $UIMenuIF("Succeeded") THEN
		BEGIN
			// Append Hidden Game Options to UI.MENU
			PRINT @101002
			SILENT
			OUTER_SPRINT $UIMenuIF("Filespec") ~%PKGNAME%/menu/ModsOptions/modohidden1.menu~
			LAUNCH_ACTION_MACRO UIMenuAppendFile
			ACTION_IF NOT $UIMenuIF("Succeeded") THEN
			BEGIN
				FAIL @101004
			END
		END ELSE BEGIN
			// Already installed
			PRINT @101003
		END
	END
	
	DEFAULT // Nothing left except Fail
		FAIL @33

END

// All done - close up
PRINT @13
SILENT
LAUNCH_ACTION_MACRO UIMenuClose
ACTION_IF NOT $UIMenuIF("Succeeded") THEN
BEGIN
	FAIL @21
END
