
// Open UI.MENU
PRINT @12
SILENT
LAUNCH_ACTION_MACRO UIMenuOpen
ACTION_IF NOT $UIMenuIF("Succeeded") THEN
BEGIN
	FAIL @20
END

ACTION_MATCH 1
WITH
	%IsBG2% %IsLeUIBG2%
	BEGIN
		// Copy override files
		PRINT @24
		SILENT
		COPY ~%PKGNAME%/copy/ModsOptions/M_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/en_HideO.lua~ ~override~

		// Append Hidden Game Options to UI.MENU
		PRINT @101002
		SILENT
		OUTER_SPRINT $UIMenuIF("Filespec") ~%PKGNAME%/menu/ModsOptions/modohidden3.menu~
		LAUNCH_ACTION_MACRO UIMenuAppendFile
		ACTION_IF NOT $UIMenuIF("Succeeded") THEN
		BEGIN
			FAIL @101004
		END
	END

	%IsTIWDonBG2% %IsTIWDonSoD%
	BEGIN
		// Copy override files
		PRINT @24
		SILENT
		COPY ~%PKGNAME%/copy/ModsOptions/M_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/en_HideO.lua~ ~override~

		// Append Hidden Game Options to UI.MENU
		PRINT @101002
		SILENT
		OUTER_SPRINT $UIMenuIF("Filespec") ~%PKGNAME%/menu/ModsOptions/modohidden5.menu~
		LAUNCH_ACTION_MACRO UIMenuAppendFile
		ACTION_IF NOT $UIMenuIF("Succeeded") THEN
		BEGIN
			FAIL @101004
		END
	END

	%IsTIWD2onBG2%
	BEGIN
		// Copy override files
		PRINT @24
		SILENT
		COPY ~%PKGNAME%/copy/ModsOptions/M_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/en_HideO.lua~ ~override~

		// Append Hidden Game Options to UI.MENU
		PRINT @101002
		SILENT
		OUTER_SPRINT $UIMenuIF("Filespec") ~%PKGNAME%/menu/ModsOptions/modohidden6.menu~
		LAUNCH_ACTION_MACRO UIMenuAppendFile
		ACTION_IF NOT $UIMenuIF("Succeeded") THEN
		BEGIN
			FAIL @101004
		END
	END

	%IsEETBG2%
	BEGIN
		// Copy override files
		PRINT @24
		SILENT
		COPY ~%PKGNAME%/copy/ModsOptions/M_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/en_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/modoimg1.bam~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/MOS5020.PVRZ~ ~override~

		// Append Hidden Game Options to UI.MENU
		PRINT @101002
		SILENT
		OUTER_SPRINT $UIMenuIF("Filespec") ~%PKGNAME%/menu/ModsOptions/modohidden3.menu~
		LAUNCH_ACTION_MACRO UIMenuAppendFile
		ACTION_IF NOT $UIMenuIF("Succeeded") THEN
		BEGIN
			FAIL @101004
		END
	END

	%IsBG2onSoD% %IsLeUISOD% %IsLeUIBG1% %IsEETLeUI%
	BEGIN
		// Copy override files
		PRINT @24
		SILENT
		COPY ~%PKGNAME%/copy/ModsOptions/en_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/M_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/GUIMGX.MOS~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/MOS5018.PVRZ~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/MODOPBG2.BAM~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/MOS5022.PVRZ~ ~override~

		// Append Hidden Game Options to UI.MENU
		PRINT @101002
		SILENT
		OUTER_SPRINT $UIMenuIF("Filespec") ~%PKGNAME%/menu/ModsOptions/modohidden2.menu~
		LAUNCH_ACTION_MACRO UIMenuAppendFile
		ACTION_IF NOT $UIMenuIF("Succeeded") THEN
		BEGIN
			FAIL @101004
		END
	END

	%IsBGEE%
	BEGIN
		PRINT @17
		SILENT
		COPY ~%PKGNAME%/copy/ModsOptions/en_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/M_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/MODOPEE.BAM~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/MOS5023.PVRZ~ ~override~

		// Append Hidden Game Options to UI.MENU
		PRINT @101002
		SILENT
		OUTER_SPRINT $UIMenuIF("Filespec") ~%PKGNAME%/menu/ModsOptions/modohidden4.menu~
		LAUNCH_ACTION_MACRO UIMenuAppendFile
		ACTION_IF NOT $UIMenuIF("Succeeded") THEN
		BEGIN
			FAIL @101004
		END
	END

	%IsSoDOverhaul%
	BEGIN
		PRINT @17
		SILENT
		COPY ~%PKGNAME%/copy/ModsOptions/en_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/M_HideO2.lua~ ~override~

		// Append Hidden Game Options to UI.MENU
		PRINT @101002
		SILENT
		OUTER_SPRINT $UIMenuIF("Filespec") ~%PKGNAME%/menu/ModsOptions/modohidden1.menu~
		LAUNCH_ACTION_MACRO UIMenuAppendFile
		ACTION_IF NOT $UIMenuIF("Succeeded") THEN
		BEGIN
			FAIL @101004
		END
	END
	
	%IsEETSoD% %IsSoD% %IsKRDS%
	BEGIN
		PRINT @17
		SILENT
		COPY ~%PKGNAME%/copy/ModsOptions/en_HideO.lua~ ~override~
		COPY ~%PKGNAME%/copy/ModsOptions/M_HideO.lua~ ~override~

		// Append Hidden Game Options to UI.MENU
		PRINT @101002
		SILENT
		OUTER_SPRINT $UIMenuIF("Filespec") ~%PKGNAME%/menu/ModsOptions/modohidden1.menu~
		LAUNCH_ACTION_MACRO UIMenuAppendFile
		ACTION_IF NOT $UIMenuIF("Succeeded") THEN
		BEGIN
			FAIL @101004
		END
	END
	
	DEFAULT // Nothing left except Fail
		FAIL @33

END

// All done - close up
PRINT @13
SILENT
LAUNCH_ACTION_MACRO UIMenuClose
ACTION_IF NOT $UIMenuIF("Succeeded") THEN
BEGIN
	FAIL @21
END
